---
title: "Getting outputs from workflows"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
    toc_float: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install AnVIL package
```{r message=FALSE, warning=FALSE, eval=FALSE}
install.packages("BiocManager")

pkg <- c("Bioconductor/AnVIL")
BiocManager::install(pkg)
```

```{r}
suppressPackageStartupMessages(library(AnVIL))
```


```{r}
# files <- avbucket()
output_dir <- "gs://fc-e3f3a1e6-da90-4ea7-9d0c-45ccc2ff0fd1/f8cfbc20-c494-4bd2-ac9b-b9c6bceb35ce/workflowMTX/4a03937d-f451-405d-b8d6-5b7a61828990"
gsutil_ls(output_dir)
```

Taxonomic Count
```{r}
TaxonomicCount_dir <- file.path(output_dir, "call-TaxonomicCount/cacheCopy/")
TaxonomicCount_files <- gsutil_ls(TaxonomicCount_dir)
gsub(TaxonomicCount_dir, "", TaxonomicCount_files)
```

Copy to the current working directory
```{r}
if (!dir.exists("TaxonomicCount")) dir.create("TaxonomicCount")
gsutil_cp(TaxonomicCount_files, "TaxonomicCount")
list.files("TaxonomicCount")
```

Access output
```{r}
counts <- read.table("TaxonomicCount/metaphlan_species_counts_table.tsv")
dim(counts)
counts
```

